services:
  coredemo:
    container_name: coredemo
    image: ${IMAGE_TAG}
    restart: always
    user: "root"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__SQLServer=${DB_CONNECTION_STR}
    networks:
      - global-rollercoin-network
    volumes:
      - /home/app/CoreDemo/logs:/app/wwwroot/logs
      - /home/app/CoreDemo/wwwroot:/app/wwwroot
      - /home/app/CoreDemo/log4net.config:/app/log4net.config:ro

networks:
  global-rollercoin-network:
    external: true